### ISSUE TITLE
shovel does not access to Beehive's RMQ

### ISSUE THREAD

**Issue by gemblerz** [waggle-sensor/waggle-node#1]
Running `waggle-node up` raises en exception from shovelctl.py. It seems the host needs certs already set up (is it?). It needs to be resolved and reflected to the README.md.

```
Traceback (most recent call last):
  File "utils/shovelctl.py", line 96, in <module>
    actions[args.action]()
  File "utils/shovelctl.py", line 73, in enable_shovels
    'value': config,
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 590, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Comment by seanshahkarami** [comment]
This appears to be caused by too much "raw" logging from the shovelctl step run during `waggle-node up`. The problem is that shovelctl will crash until the local rabbitmq API endpoint is up.

It still succeeds because of the [retry loop](https://github.com/waggle-sensor/waggle-node/blob/1b6588828bcf3ca4f8a658a572a80eda4e1fa50d/waggle-node#L18), but it's confusing and verbose from all the exceptions.

I've added a "wait for rabbitmq" step in the shovelctl process to clean this up.
